# Generated by Django 5.0.3 on 2024-03-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Player_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(default='', upload_to='Bid_Auction/static/images'),
        ),
    ]
