# Generated by Django 5.0.3 on 2024-03-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Player_data', '0002_player_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(default='', upload_to='player/images'),
        ),
    ]
